# Generated by Django 5.1.4 on 2025-01-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtask_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
    ]
