# Generated by Django 5.1.4 on 2025-01-01 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_task_parent_task_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtensionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_by', models.CharField(max_length=100)),
                ('new_due_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_logs', to='taskmanager.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_extension_logs',
            field=models.ManyToManyField(blank=True, related_name='tasks_with_extension', to='taskmanager.deadlineextensionlog'),
        ),
    ]
