# Generated by Django 5.1.4 on 2025-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_deadlineextensionlog_task_deadline_extension_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('When Free', 'When Free'), ('Next Week', 'Next Week'), ('ASAP', 'ASAP'), ('URGENT', 'URGENT')], default='When Free', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
