# Generated by Django 5.1.4 on 2025-01-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0013_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadlineextensionlog',
            old_name='extended_by',
            new_name='request_by',
        ),
    ]
