# Generated by Django 5.1.4 on 2025-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0015_alter_deadlineextensionlog_request_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadlineextensionlog',
            old_name='new_due_date',
            new_name='new_deadline',
        ),
        migrations.AddField(
            model_name='deadlineextensionlog',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deadlineextensionlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
